### ISSUE TITLE
Mixin conflict with Serious Player Animations mod

### ISSUE THREAD

**Issue by N-thing** [muon-rw/Medieval-Origins-Old#108]
Crash client - conflict elytra mixins with serious animations mod. Issue from 6.4.0 version
[crash-2024-07-01_14.51.26-client.txt](https://github.com/user-attachments/files/16051179/crash-2024-07-01_14.51.26-client.txt)

**Comment by muon-rw** [comment]
I did try to write this mixin in the most compatible way possible, but it looks like they @Overwrite the entirety of setupAnim "Because it wasn't working"... This will break a *lot* of other mods, not just mine. 

Probably not something I'll add a workaround for on my end. 

I would recommend you use [Animation Overhaul](https://www.curseforge.com/minecraft/mc-mods/animationoverhaul) instead.
