### ISSUE TITLE
Necromancer/Plague Victim rework

### ISSUE THREAD

**Issue by WPeanuts** [muon-rw/Medieval-Origins-Old#17]
Necromancer doesn't really make sense for an origin name, something like Lich would work better since its an actual race and still relates to necromancy. Necromancy itself is a job/occupation 

Plague Victim is the same way, Skaven (Rat-folk) would make more sense because it still directly relates to the original origin. A Victim could be anyone.

The origins themselves are great, I'm just getting complaints from people that the names doesn't make sense as an origin.

**Comment by muon-rw** [comment]
I appreciate the suggestions and I agree! 

This is actually something I'm already implementing in my rework, but I was initially thinking of combining some of the abilities from Necromancer and Plague Victim into an undead race called "Draugr." Not sure what it'll end up as

I may keep something named Necromancer as a class, as I'm planning to add a separate class layer.

**Comment by CatAndPaste** [comment]
I think Undead (Draugr) can stand on its own and be a great addition :3 

Currently I'm working on Plague Bringer rework for modpack we play with friends:
Difficulty: 3, Recommended ONLY for experienced Minecraft players.

**Dead Man's Diet**
Being closer to undead than living creature, you are not experiencing hunger. Food restores health instead of saturation.

**Skin infection**
Festering sores cause terrible pain when you wear armor. Each piece of armor reduces your maximum health by 1 heart.

Ulcers prevent you from sleeping. However, phantoms are no longer interested in you.

**Fading Life**
Your maximum health is reduced to 5 hearts.

The undead no longer see you as a living creature and will not attack first.

**Spread the plague** [Passive] [Spawns smoke and potion particles on trigger]
When you are attacked in melee, there is a 25% chance that you and the attacker will receive a disease debuff: hunger, nausea, poison or weakness. When you attack a creature in melee combat, there is a 5% chance of triggering this effect.

**Suppress the pain** [Passive, stacks] [GUI progress bar]
Hunger has no effect on you.

For every two nights you survive, you gain 1% chance that poison, weakness or nausea effects won't trigger on you. After you survive 200 nights, poison, weakness and nausea no longer affect you (including Spread the plague effect) and you also get Resistance I.

You lose all the progress on death.

**Unwanted contact**
Villagers will not trade with you directly and will try to run away. When you kill the villager in melee combat, there is 25% chance they will become zombified villager instead of dying.

**Afterlife**
When you die, there is a 50% chance zombie will spawn on place of your death with all your effects and maximum health.

**Comment by muon-rw** [comment]
implemented in dev!
