### ISSUE TITLE
Pixie Accessibility, High Elf balance, Ogre balance

### ISSUE THREAD

**Issue by JameDemon** [muon-rw/Medieval-Origins-Old#33]
Ogre: Changing it so they don't have to use axes and insted could get benefits from using all melee weapons would help a lot with playing them in modpacks. That way they won't feel so samey. 

High Elf: These guys feel like they're in an odd place. One of their perks being Instant Cure feels like it's a waste of a power, the usual method is very cheap to use instead. I'd recommend replacing this with something else. Also as far as I'm aware the only magic damage in the game is potions? How do we play these guys to good efect? Potions don't really stack like arrows. 

Pixie: How do I disable the decorative stuff and sounds that play when they use their powers? It's getting annoying, and I don't like them trailing particles around like that.

**Comment by muon-rw** [comment]
Pixie sounds can be disabled by lowering the "Player" category in your sound settings - I'll look into splitting them into a separate power along with the particles so that they can be disabled completely. 

High Elf, honestly, was only designed with magic mods in mind. I *may* just make it only load conditionally if one is present, since as you say, there's not many magic mechanics in vanilla. Alternatively I may give them some of their own more combat-oriented spells. I can definitely make instant cure cheaper - It initially cost nothing and I was more concerned about it being too overpowered, considering how strong villager trading can be. If you have suggestions here, I'm open to them.

I'll try to figure out a better idea for Ogres; I do feel like axes are more fitting thematically, but you're right that the gear options for them can feel pretty boring in comparison. There's also the similar problem of axes generally being treated as tools, not weapons

**Comment by JameDemon** [comment]
Oh, in that case I think the High Elf's concept might just be a lost cause at that point actually. There's not many magic mods that actually use magic damage at all. The most I can remember is some of them also have potions but that falls into the same issue as vanilla. Ars Noveau for instance I don't think ever uses it and that's like a flag ship magic mod or something in modern versions. That is unless you just decide to give them spells or something. 

As for the ogre problem I reccomend just giving them a boost to melee damage in general, they're big bulky guys or whatver, it doesn't make much sense to only have it on aces.

**Comment by muon-rw** [comment]
Looks like you’re right, even Iron’s Spellbooks doesn’t actually use magic damage (though fabric magic mods generally do). I’ll probably just directly increase their damage types or spell power instead. 

These are all planned for next update
